title: Alex Bell # your name (or website title) here
logo: "/images/profile_pic.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist seeking out insights through analysis and modeling.  I simplify complex processes to make them more understandable. 
  <br><br>
  After years of working in the financial field, I became more and more interested in the World of Data and the answers it holds. I enrolled full time in a Data Science program and now after completing, plan to use my knowledge to break open the insights that data holds.  
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-f-bell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
